name: wulap_application
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  dotted_border: ^2.0.0+3
  flutter_staggered_grid_view: ^0.4.1
  intl: ^0.18.0
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  google_sign_in: ^5.4.2
  sign_in_button: ^3.2.0
  http: ^1.1.0
  email_auth: ^1.1.1
  firebase_dynamic_links: ^5.4.4
  awesome_dialog: ^3.1.0
  image_picker: ^1.0.4
  firebase_storage: ^11.5.1
  get: ^4.6.6
  xml: ^6.3.0
  path: ^1.8.3
  firebase_app_check: ^0.2.1+4
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  hive:
  hive_flutter:
  uuid: ^4.2.1
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/logo_foreground.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
    - family: Outfit
      fonts:
        - asset: assets/fonts/OutfitSemiBold.ttf
          weight: 600
        - asset: assets/fonts/OutfitRegular.ttf
          weight: 400
        - asset: assets/fonts/OutfitBold.ttf
          weight: 700
        - asset: assets/fonts/OutfitMedium.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZeeRegular.ttf
          weight: 400
        - asset: assets/fonts/ABeeZeeItalic.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoMedium.ttf
          weight: 500
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
